server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:4000/;
    }

    location /accounts/ {
        proxy_pass http://account-service:5000/;
    }
    location /payments/ {
    proxy_pass http://payment-service:6000/;
    }
}
